version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: llm_platform_postgres
    environment:
      POSTGRES_DB: llm_platform
      POSTGRES_USER: llm_user
      POSTGRES_PASSWORD: llm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llm_user -d llm_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: llm_platform_redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: llm_platform_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://llm_user:llm_password@postgres:5432/llm_platform
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: 